/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateReminderInput {
  'scheduledTime' : Timestamp,
  'message' : string,
  'linkedTaskId' : [] | [TaskId],
}
export interface CreateTaskInput {
  'title' : string,
  'subject' : string,
  'dueDate' : Timestamp,
  'durationMinutes' : bigint,
}
export interface DailyStudyData { 'date' : string, 'totalMinutes' : bigint }
export interface Quiz {
  'id' : QuizId,
  'subject' : string,
  'createdAt' : Timestamp,
  'taskId' : TaskId,
  'questions' : Array<QuizQuestion>,
}
export interface QuizAnswerSubmission {
  'answers' : Array<[bigint, bigint]>,
  'quizId' : QuizId,
}
export type QuizId = bigint;
export interface QuizOption { 'id' : bigint, 'text' : string }
export interface QuizQuestion {
  'id' : bigint,
  'correctOptionId' : bigint,
  'question' : string,
  'options' : Array<QuizOption>,
}
export interface QuizResult {
  'completedAt' : Timestamp,
  'subject' : string,
  'score' : bigint,
  'taskId' : TaskId,
  'totalQuestions' : bigint,
  'quizId' : QuizId,
}
export interface Reminder {
  'id' : ReminderId,
  'status' : ReminderStatus,
  'snoozeUntil' : [] | [Timestamp],
  'scheduledTime' : Timestamp,
  'createdAt' : Timestamp,
  'message' : string,
  'linkedTaskId' : [] | [TaskId],
}
export type ReminderId = bigint;
export type ReminderStatus = { 'pending' : null } |
  { 'snoozed' : null } |
  { 'dismissed' : null };
export type SessionId = bigint;
export type SessionStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'paused' : null };
export interface StudySession {
  'id' : SessionId,
  'startTime' : Timestamp,
  'status' : SessionStatus,
  'pausedAt' : [] | [Timestamp],
  'endTime' : [] | [Timestamp],
  'totalElapsedSeconds' : bigint,
  'taskId' : TaskId,
}
export interface StudyStats {
  'currentStreakDays' : bigint,
  'totalStudyMinutes' : bigint,
  'totalCompletedTasks' : bigint,
}
export interface SubjectTime { 'subject' : string, 'totalMinutes' : bigint }
export interface Task {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'durationMinutes' : bigint,
}
export type TaskId = bigint;
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export interface UpdateTaskInput {
  'id' : TaskId,
  'title' : [] | [string],
  'subject' : [] | [string],
  'dueDate' : [] | [Timestamp],
  'durationMinutes' : [] | [bigint],
}
export interface _SERVICE {
  'completeSession' : ActorMethod<[SessionId], boolean>,
  'createReminder' : ActorMethod<[CreateReminderInput], Reminder>,
  'createTask' : ActorMethod<[CreateTaskInput], Task>,
  'deleteTask' : ActorMethod<[TaskId], boolean>,
  'dismissReminder' : ActorMethod<[ReminderId], boolean>,
  'generateQuiz' : ActorMethod<[TaskId], [] | [Quiz]>,
  'getActiveSessions' : ActorMethod<[], Array<StudySession>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getDailyStudyData' : ActorMethod<[bigint], Array<DailyStudyData>>,
  'getQuizHistory' : ActorMethod<[], Array<QuizResult>>,
  'getStudyStats' : ActorMethod<[], StudyStats>,
  'getStudyTimeBySubject' : ActorMethod<[], Array<SubjectTime>>,
  'getTask' : ActorMethod<[TaskId], [] | [Task]>,
  'getUpcomingReminders' : ActorMethod<[], Array<Reminder>>,
  'pauseSession' : ActorMethod<[SessionId], boolean>,
  'resumeSession' : ActorMethod<[SessionId], boolean>,
  'snoozeReminder' : ActorMethod<[ReminderId, Timestamp], boolean>,
  'startSession' : ActorMethod<[TaskId], [] | [StudySession]>,
  'submitQuizAnswers' : ActorMethod<[QuizAnswerSubmission], [] | [QuizResult]>,
  'updateTask' : ActorMethod<[UpdateTaskInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];