/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const TaskId = IDL.Nat;
export const CreateReminderInput = IDL.Record({
  'scheduledTime' : Timestamp,
  'message' : IDL.Text,
  'linkedTaskId' : IDL.Opt(TaskId),
});
export const ReminderId = IDL.Nat;
export const ReminderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'snoozed' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'status' : ReminderStatus,
  'snoozeUntil' : IDL.Opt(Timestamp),
  'scheduledTime' : Timestamp,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'linkedTaskId' : IDL.Opt(TaskId),
});
export const CreateTaskInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'dueDate' : Timestamp,
  'durationMinutes' : IDL.Nat,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'durationMinutes' : IDL.Nat,
});
export const QuizId = IDL.Nat;
export const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'correctOptionId' : IDL.Nat,
  'question' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'taskId' : TaskId,
  'questions' : IDL.Vec(QuizQuestion),
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'paused' : IDL.Null,
});
export const StudySession = IDL.Record({
  'id' : SessionId,
  'startTime' : Timestamp,
  'status' : SessionStatus,
  'pausedAt' : IDL.Opt(Timestamp),
  'endTime' : IDL.Opt(Timestamp),
  'totalElapsedSeconds' : IDL.Nat,
  'taskId' : TaskId,
});
export const DailyStudyData = IDL.Record({
  'date' : IDL.Text,
  'totalMinutes' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'completedAt' : Timestamp,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
  'taskId' : TaskId,
  'totalQuestions' : IDL.Nat,
  'quizId' : QuizId,
});
export const StudyStats = IDL.Record({
  'currentStreakDays' : IDL.Nat,
  'totalStudyMinutes' : IDL.Nat,
  'totalCompletedTasks' : IDL.Nat,
});
export const SubjectTime = IDL.Record({
  'subject' : IDL.Text,
  'totalMinutes' : IDL.Nat,
});
export const QuizAnswerSubmission = IDL.Record({
  'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'quizId' : QuizId,
});
export const UpdateTaskInput = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Opt(IDL.Text),
  'subject' : IDL.Opt(IDL.Text),
  'dueDate' : IDL.Opt(Timestamp),
  'durationMinutes' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'completeSession' : IDL.Func([SessionId], [IDL.Bool], []),
  'createReminder' : IDL.Func([CreateReminderInput], [Reminder], []),
  'createTask' : IDL.Func([CreateTaskInput], [Task], []),
  'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'dismissReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
  'generateQuiz' : IDL.Func([TaskId], [IDL.Opt(Quiz)], []),
  'getActiveSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getDailyStudyData' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DailyStudyData)],
      ['query'],
    ),
  'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getStudyStats' : IDL.Func([], [StudyStats], ['query']),
  'getStudyTimeBySubject' : IDL.Func([], [IDL.Vec(SubjectTime)], ['query']),
  'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
  'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'pauseSession' : IDL.Func([SessionId], [IDL.Bool], []),
  'resumeSession' : IDL.Func([SessionId], [IDL.Bool], []),
  'snoozeReminder' : IDL.Func([ReminderId, Timestamp], [IDL.Bool], []),
  'startSession' : IDL.Func([TaskId], [IDL.Opt(StudySession)], []),
  'submitQuizAnswers' : IDL.Func(
      [QuizAnswerSubmission],
      [IDL.Opt(QuizResult)],
      [],
    ),
  'updateTask' : IDL.Func([UpdateTaskInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const TaskId = IDL.Nat;
  const CreateReminderInput = IDL.Record({
    'scheduledTime' : Timestamp,
    'message' : IDL.Text,
    'linkedTaskId' : IDL.Opt(TaskId),
  });
  const ReminderId = IDL.Nat;
  const ReminderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'snoozed' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'status' : ReminderStatus,
    'snoozeUntil' : IDL.Opt(Timestamp),
    'scheduledTime' : Timestamp,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'linkedTaskId' : IDL.Opt(TaskId),
  });
  const CreateTaskInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'dueDate' : Timestamp,
    'durationMinutes' : IDL.Nat,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'dueDate' : Timestamp,
    'durationMinutes' : IDL.Nat,
  });
  const QuizId = IDL.Nat;
  const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'correctOptionId' : IDL.Nat,
    'question' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const Quiz = IDL.Record({
    'id' : QuizId,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'taskId' : TaskId,
    'questions' : IDL.Vec(QuizQuestion),
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'paused' : IDL.Null,
  });
  const StudySession = IDL.Record({
    'id' : SessionId,
    'startTime' : Timestamp,
    'status' : SessionStatus,
    'pausedAt' : IDL.Opt(Timestamp),
    'endTime' : IDL.Opt(Timestamp),
    'totalElapsedSeconds' : IDL.Nat,
    'taskId' : TaskId,
  });
  const DailyStudyData = IDL.Record({
    'date' : IDL.Text,
    'totalMinutes' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'completedAt' : Timestamp,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
    'taskId' : TaskId,
    'totalQuestions' : IDL.Nat,
    'quizId' : QuizId,
  });
  const StudyStats = IDL.Record({
    'currentStreakDays' : IDL.Nat,
    'totalStudyMinutes' : IDL.Nat,
    'totalCompletedTasks' : IDL.Nat,
  });
  const SubjectTime = IDL.Record({
    'subject' : IDL.Text,
    'totalMinutes' : IDL.Nat,
  });
  const QuizAnswerSubmission = IDL.Record({
    'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'quizId' : QuizId,
  });
  const UpdateTaskInput = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Opt(IDL.Text),
    'subject' : IDL.Opt(IDL.Text),
    'dueDate' : IDL.Opt(Timestamp),
    'durationMinutes' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'completeSession' : IDL.Func([SessionId], [IDL.Bool], []),
    'createReminder' : IDL.Func([CreateReminderInput], [Reminder], []),
    'createTask' : IDL.Func([CreateTaskInput], [Task], []),
    'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'dismissReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
    'generateQuiz' : IDL.Func([TaskId], [IDL.Opt(Quiz)], []),
    'getActiveSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getDailyStudyData' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DailyStudyData)],
        ['query'],
      ),
    'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getStudyStats' : IDL.Func([], [StudyStats], ['query']),
    'getStudyTimeBySubject' : IDL.Func([], [IDL.Vec(SubjectTime)], ['query']),
    'getTask' : IDL.Func([TaskId], [IDL.Opt(Task)], ['query']),
    'getUpcomingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'pauseSession' : IDL.Func([SessionId], [IDL.Bool], []),
    'resumeSession' : IDL.Func([SessionId], [IDL.Bool], []),
    'snoozeReminder' : IDL.Func([ReminderId, Timestamp], [IDL.Bool], []),
    'startSession' : IDL.Func([TaskId], [IDL.Opt(StudySession)], []),
    'submitQuizAnswers' : IDL.Func(
        [QuizAnswerSubmission],
        [IDL.Opt(QuizResult)],
        [],
      ),
    'updateTask' : IDL.Func([UpdateTaskInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };