/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface SubjectTime {
    subject: string;
    totalMinutes: bigint;
}
export type ReminderId = bigint;
export interface DailyStudyData {
    date: string;
    totalMinutes: bigint;
}
export interface QuizQuestion {
    id: bigint;
    correctOptionId: bigint;
    question: string;
    options: Array<QuizOption>;
}
export interface CreateTaskInput {
    title: string;
    subject: string;
    dueDate: Timestamp;
    durationMinutes: bigint;
}
export interface Task {
    id: TaskId;
    status: TaskStatus;
    title: string;
    subject: string;
    createdAt: Timestamp;
    dueDate: Timestamp;
    durationMinutes: bigint;
}
export interface Quiz {
    id: QuizId;
    subject: string;
    createdAt: Timestamp;
    taskId: TaskId;
    questions: Array<QuizQuestion>;
}
export type SessionId = bigint;
export interface QuizResult {
    completedAt: Timestamp;
    subject: string;
    score: bigint;
    taskId: TaskId;
    totalQuestions: bigint;
    quizId: QuizId;
}
export interface StudyStats {
    currentStreakDays: bigint;
    totalStudyMinutes: bigint;
    totalCompletedTasks: bigint;
}
export interface Reminder {
    id: ReminderId;
    status: ReminderStatus;
    snoozeUntil?: Timestamp;
    scheduledTime: Timestamp;
    createdAt: Timestamp;
    message: string;
    linkedTaskId?: TaskId;
}
export type TaskId = bigint;
export interface StudySession {
    id: SessionId;
    startTime: Timestamp;
    status: SessionStatus;
    pausedAt?: Timestamp;
    endTime?: Timestamp;
    totalElapsedSeconds: bigint;
    taskId: TaskId;
}
export interface QuizOption {
    id: bigint;
    text: string;
}
export interface CreateReminderInput {
    scheduledTime: Timestamp;
    message: string;
    linkedTaskId?: TaskId;
}
export interface UpdateTaskInput {
    id: TaskId;
    title?: string;
    subject?: string;
    dueDate?: Timestamp;
    durationMinutes?: bigint;
}
export interface QuizAnswerSubmission {
    answers: Array<[bigint, bigint]>;
    quizId: QuizId;
}
export type QuizId = bigint;
export enum ReminderStatus {
    pending = "pending",
    snoozed = "snoozed",
    dismissed = "dismissed"
}
export enum SessionStatus {
    active = "active",
    completed = "completed",
    paused = "paused"
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    completeSession(sessionId: SessionId): Promise<boolean>;
    createReminder(input: CreateReminderInput): Promise<Reminder>;
    createTask(input: CreateTaskInput): Promise<Task>;
    deleteTask(id: TaskId): Promise<boolean>;
    dismissReminder(id: ReminderId): Promise<boolean>;
    generateQuiz(taskId: TaskId): Promise<Quiz | null>;
    getActiveSessions(): Promise<Array<StudySession>>;
    getAllTasks(): Promise<Array<Task>>;
    getDailyStudyData(days: bigint): Promise<Array<DailyStudyData>>;
    getQuizHistory(): Promise<Array<QuizResult>>;
    getStudyStats(): Promise<StudyStats>;
    getStudyTimeBySubject(): Promise<Array<SubjectTime>>;
    getTask(id: TaskId): Promise<Task | null>;
    getUpcomingReminders(): Promise<Array<Reminder>>;
    pauseSession(sessionId: SessionId): Promise<boolean>;
    resumeSession(sessionId: SessionId): Promise<boolean>;
    snoozeReminder(id: ReminderId, snoozeUntil: Timestamp): Promise<boolean>;
    startSession(taskId: TaskId): Promise<StudySession | null>;
    submitQuizAnswers(submission: QuizAnswerSubmission): Promise<QuizResult | null>;
    updateTask(input: UpdateTaskInput): Promise<boolean>;
}
import type { CreateReminderInput as _CreateReminderInput, Quiz as _Quiz, QuizResult as _QuizResult, Reminder as _Reminder, ReminderId as _ReminderId, ReminderStatus as _ReminderStatus, SessionId as _SessionId, SessionStatus as _SessionStatus, StudySession as _StudySession, Task as _Task, TaskId as _TaskId, TaskStatus as _TaskStatus, Timestamp as _Timestamp, UpdateTaskInput as _UpdateTaskInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeSession(arg0: SessionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeSession(arg0);
            return result;
        }
    }
    async createReminder(arg0: CreateReminderInput): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(to_candid_CreateReminderInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Reminder_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(to_candid_CreateReminderInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Reminder_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: CreateTaskInput): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0);
                return from_candid_Task_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0);
            return from_candid_Task_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async dismissReminder(arg0: ReminderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReminder(arg0);
            return result;
        }
    }
    async generateQuiz(arg0: TaskId): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQuiz(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQuiz(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveSessions(): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSessions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSessions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyStudyData(arg0: bigint): Promise<Array<DailyStudyData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyStudyData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyStudyData(arg0);
            return result;
        }
    }
    async getQuizHistory(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizHistory();
            return result;
        }
    }
    async getStudyStats(): Promise<StudyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyStats();
            return result;
        }
    }
    async getStudyTimeBySubject(): Promise<Array<SubjectTime>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyTimeBySubject();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyTimeBySubject();
            return result;
        }
    }
    async getTask(arg0: TaskId): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingReminders();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingReminders();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async pauseSession(arg0: SessionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseSession(arg0);
            return result;
        }
    }
    async resumeSession(arg0: SessionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeSession(arg0);
            return result;
        }
    }
    async snoozeReminder(arg0: ReminderId, arg1: Timestamp): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.snoozeReminder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.snoozeReminder(arg0, arg1);
            return result;
        }
    }
    async startSession(arg0: TaskId): Promise<StudySession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuizAnswers(arg0: QuizAnswerSubmission): Promise<QuizResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswers(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswers(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: UpdateTaskInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(to_candid_UpdateTaskInput_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(to_candid_UpdateTaskInput_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ReminderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderStatus): ReminderStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Reminder_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reminder): Reminder {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StudySession_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudySession): StudySession {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudySession]): StudySession | null {
    return value.length === 0 ? null : from_candid_StudySession_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizResult]): QuizResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskId]): TaskId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    subject: string;
    createdAt: _Timestamp;
    dueDate: _Timestamp;
    durationMinutes: bigint;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    subject: string;
    createdAt: Timestamp;
    dueDate: Timestamp;
    durationMinutes: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n11(_uploadFile, _downloadFile, value.status),
        title: value.title,
        subject: value.subject,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        durationMinutes: value.durationMinutes
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    startTime: _Timestamp;
    status: _SessionStatus;
    pausedAt: [] | [_Timestamp];
    endTime: [] | [_Timestamp];
    totalElapsedSeconds: bigint;
    taskId: _TaskId;
}): {
    id: SessionId;
    startTime: Timestamp;
    status: SessionStatus;
    pausedAt?: Timestamp;
    endTime?: Timestamp;
    totalElapsedSeconds: bigint;
    taskId: TaskId;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_SessionStatus_n17(_uploadFile, _downloadFile, value.status),
        pausedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pausedAt)),
        endTime: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.endTime)),
        totalElapsedSeconds: value.totalElapsedSeconds,
        taskId: value.taskId
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReminderId;
    status: _ReminderStatus;
    snoozeUntil: [] | [_Timestamp];
    scheduledTime: _Timestamp;
    createdAt: _Timestamp;
    message: string;
    linkedTaskId: [] | [_TaskId];
}): {
    id: ReminderId;
    status: ReminderStatus;
    snoozeUntil?: Timestamp;
    scheduledTime: Timestamp;
    createdAt: Timestamp;
    message: string;
    linkedTaskId?: TaskId;
} {
    return {
        id: value.id,
        status: from_candid_ReminderStatus_n5(_uploadFile, _downloadFile, value.status),
        snoozeUntil: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.snoozeUntil)),
        scheduledTime: value.scheduledTime,
        createdAt: value.createdAt,
        message: value.message,
        linkedTaskId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.linkedTaskId))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    paused: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "completed" in value ? SessionStatus.completed : "paused" in value ? SessionStatus.paused : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    snoozed: null;
} | {
    dismissed: null;
}): ReminderStatus {
    return "pending" in value ? ReminderStatus.pending : "snoozed" in value ? ReminderStatus.snoozed : "dismissed" in value ? ReminderStatus.dismissed : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudySession>): Array<StudySession> {
    return value.map((x)=>from_candid_StudySession_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reminder>): Array<Reminder> {
    return value.map((x)=>from_candid_Reminder_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CreateReminderInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateReminderInput): _CreateReminderInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTaskInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTaskInput): _UpdateTaskInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduledTime: Timestamp;
    message: string;
    linkedTaskId?: TaskId;
}): {
    scheduledTime: _Timestamp;
    message: string;
    linkedTaskId: [] | [_TaskId];
} {
    return {
        scheduledTime: value.scheduledTime,
        message: value.message,
        linkedTaskId: value.linkedTaskId ? candid_some(value.linkedTaskId) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TaskId;
    title?: string;
    subject?: string;
    dueDate?: Timestamp;
    durationMinutes?: bigint;
}): {
    id: _TaskId;
    title: [] | [string];
    subject: [] | [string];
    dueDate: [] | [_Timestamp];
    durationMinutes: [] | [bigint];
} {
    return {
        id: value.id,
        title: value.title ? candid_some(value.title) : candid_none(),
        subject: value.subject ? candid_some(value.subject) : candid_none(),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        durationMinutes: value.durationMinutes ? candid_some(value.durationMinutes) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
